export default {
  SIT: {
    defaultPkDn: [
      {
        pk: "jrYYVrWZWVq",
        dn: "Rview-FDJ-N1",
        key: "first",
      },
      {
        pk: "jrYYVrWZWVq",
        dn: "Rview--FDJ-N2",
        key: "second",
      },
    ],
    alternatorDatas: [
      {
        name: "first_ryw",
        key: "jrYYVrWZWVq_Rview-FDJ-N1_ryw",
        lines: [50, 378, 228, 378, 424, 517],
        circles: [
          { x: 228, y: 378 },
          { x: 424, y: 517 },
        ],
        tipsPosition: {
          x: 68,
          y: 355,
        },
        ract: [{ x: 228, y: 378 }],
        text: [
          {
            x: 68,
            y: 355,
            text: "燃油位:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 124,
            y: 354,
            text: "80.00",
            unit: "%",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "first_jyy",
        key: "jrYYVrWZWVq_Rview-FDJ-N1_jyy",
        lines: [77, 252, 235, 252, 369, 450],
        circles: [
          { x: 235, y: 252 },
          { x: 369, y: 450 },
        ],
        tipsPosition: {
          x: 88,
          y: 227,
        },
        ract: [{ x: 235, y: 252 }],
        text: [
          {
            x: 88,
            y: 227,
            text: "机油压:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 145,
            y: 226,
            text: "3.5Bar",
            unit: "Bar",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "first_sw",
        key: "jrYYVrWZWVq_Rview-FDJ-N1_sw",
        lines: [301, 304, 459, 304, 505, 491],
        circles: [
          { x: 459, y: 304 },
          { x: 505, y: 491 },
        ],
        tipsPosition: {
          x: 312,
          y: 279,
        },
        ract: [{ x: 459, y: 304 }],
        text: [
          {
            x: 312,
            y: 279,
            text: "水温:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 351,
            y: 278,
            text: "27.00℃",
            unit: "℃",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "first_dldy",
        key: "jrYYVrWZWVq_Rview-FDJ-N1_dldy",
        lines: [199, 715, 381, 715, 475, 619],
        circles: [
          { x: 381, y: 715 },
          { x: 475, y: 619 },
        ],
        tipsPosition: {
          x: 204,
          y: 689,
        },
        ract: [{ x: 381, y: 715 }],
        text: [
          {
            x: 204,
            y: 689,
            text: "电流电压:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 276,
            y: 688,
            text: "27.00V",
            unit: "V",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "first_fdpl",
        key: "jrYYVrWZWVq_Rview-FDJ-N1_fdpl",
        lines: [287, 795, 489, 795, 605, 621],
        circles: [
          { x: 489, y: 795 },
          { x: 605, y: 621 },
        ],
        tipsPosition: {
          x: 296,
          y: 769,
        },
        ract: [{ x: 489, y: 795 }],
        text: [
          {
            x: 296,
            y: 769,
            text: "发电频率:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 369,
            y: 768,
            text: "18.88Hz",
            unit: "Hz",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "second_jyy",
        key: "jrYYVrWZWVq_Rview--FDJ-N2_jyy",
        lines: [383, 223, 568, 223, 611, 422],
        circles: [
          { x: 568, y: 223 },
          { x: 611, y: 422 },
        ],
        tipsPosition: {
          x: 419,
          y: 199,
        },
        ract: [{ x: 568, y: 223 }],
        text: [
          {
            x: 419,
            y: 199,
            text: "机油压:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 473,
            y: 198,
            text: "3.5Bar",
            unit: "Bar",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "second_ryw",
        key: "jrYYVrWZWVq_Rview--FDJ-N2_ryw",
        state: "",
        errorDatas: {
          // warnCount: "",
          // warnTime: 888,
        },
        tipsPosition: {
          x: 773,
          y: 160,
        },
        lines: [671, 486, 744, 181, 966, 181],
        circles: [
          { x: 744, y: 181 },
          { x: 671, y: 486 },
        ],
        ract: [{ x: 744, y: 181 }],
        text: [
          {
            x: 773,
            y: 160,
            text: "燃油位:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 825,
            y: 159,
            text: " 80.00%",
            unit: "%",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "second_sw",
        key: "jrYYVrWZWVq_Rview--FDJ-N2_sw",
        lines: [762, 454, 827, 285, 1009, 285],
        circles: [
          { x: 827, y: 285 },
          { x: 762, y: 454 },
        ],
        tipsPosition: {
          x: 855,
          y: 262,
        },
        ract: [{ x: 827, y: 285 }],
        text: [
          {
            x: 855,
            y: 262,
            text: "水温:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 893,
            y: 261,
            text: "27.00℃",
            unit: "℃",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "second_dldy",
        key: "jrYYVrWZWVq_Rview--FDJ-N2_dldy",
        state: "",
        errorDatas: {
          // warnCount: 1,
          // warnTime: 888,
        },
        tipsPosition: {
          x: 843,
          y: 377,
        },
        lines: [736, 587, 817, 399, 998, 399],
        circles: [
          { x: 817, y: 399 },
          { x: 736, y: 587 },
        ],
        ract: [{ x: 817, y: 399 }],
        text: [
          {
            x: 843,
            y: 377,
            text: "电流电压:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 910,
            y: 376,
            text: " 27.00V",
            unit: "V",
            fontSize: 19,
            textDecoration: "111",
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "second_fdpl",
        key: "jrYYVrWZWVq_Rview--FDJ-N2_fdpl",
        lines: [869, 574, 821, 777, 1023, 777],
        circles: [
          { x: 821, y: 777 },
          { x: 869, y: 574 },
        ],
        tipsPosition: {
          x: 847,
          y: 755,
        },
        ract: [{ x: 821, y: 777 }],
        text: [
          {
            x: 847,
            y: 755,
            text: "发电频率:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 920,
            y: 754,
            text: "18.88Hz",
            unit: "Hz",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
    ],
    monitorDatas: {
      activeTabs: "oneAlternator",
      activeMonitorState: "ONLINE",
      tabs: [{ label: "1#配电房", value: "oneAlternator" }],
      videoUrl: "https://uat.rlinkiot.com/live/live/34020000001320000024@34020000001320000024.flv",
      bannerList: [
        {
          pkdn: "irXZyrbZ7BP:Rview-Camera2",
          label: "锦绣办公室监控",
          url: "https://uat.rlinkiot.com/live/live/34020000001320000024@34020000001320000024.flv",
          background: require("../assets/images/banner_background_temp.jpg"),
          monitorState: "ONLINE",
          active: true,
        },
        {
          label: "会议室监控视频",
          pkdn: "irXZyrbZ7BP:Rview-Camera1",
          url: "https://uat.rlinkiot.com/live/live/34020000001320000025@34020000001310000001.flv",
          background: require("../assets/images/banner_background_temp2.jpg"),
          monitorState: "ONLINE",
          active: false,
        },
      ],
      defaultCard: "Rview-WSD-0004",
      cardList: [
        {
          title: "发电机房-1#温湿度",
          productKey: "HrXb9rXZKwd",
          deviceName: "Rview-WSD-0004",
          temperature: 0,
          humidity: 0,
        },
        {
          title: "发电机房-2#温湿度",
          productKey: "HrXb9rXZKwd",
          deviceName: "Rview-WSD-0005",
          temperature: 0,
          humidity: 0,
        },
      ],
    },
  },
  UAT: {
    defaultPkDn: [
      {
        pk: "jrYYVrWZWVq",
        dn: "JX1-FDJ-N1",
        key: "first",
      },
      {
        pk: "jrYYVrWZWVq",
        dn: "JX1-FDJ-N2",
        key: "second",
      },
    ],
    alternatorDatas: [
      {
        name: "first_ryw",
        key: "jrYYVrWZWVq_JX1-FDJ-N1_ryw",
        lines: [50, 378, 228, 378, 424, 517],
        circles: [
          { x: 228, y: 378 },
          { x: 424, y: 517 },
        ],
        tipsPosition: {
          x: 68,
          y: 355,
        },
        ract: [{ x: 228, y: 378 }],
        text: [
          {
            x: 68,
            y: 355,
            text: "燃油位:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 124,
            y: 354,
            text: "80.00",
            unit: "%",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "first_jyy",
        key: "jrYYVrWZWVq_JX1-FDJ-N1_jyy",
        lines: [77, 252, 235, 252, 369, 450],
        circles: [
          { x: 235, y: 252 },
          { x: 369, y: 450 },
        ],
        tipsPosition: {
          x: 88,
          y: 227,
        },
        ract: [{ x: 235, y: 252 }],
        text: [
          {
            x: 88,
            y: 227,
            text: "机油压:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 145,
            y: 226,
            text: "3.5Bar",
            unit: "Bar",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "first_sw",
        key: "jrYYVrWZWVq_JX1-FDJ-N1_sw",
        lines: [301, 304, 459, 304, 505, 491],
        circles: [
          { x: 459, y: 304 },
          { x: 505, y: 491 },
        ],
        tipsPosition: {
          x: 312,
          y: 279,
        },
        ract: [{ x: 459, y: 304 }],
        text: [
          {
            x: 312,
            y: 279,
            text: "水温:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 351,
            y: 278,
            text: "27.00℃",
            unit: "℃",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "first_dldy",
        key: "jrYYVrWZWVq_JX1-FDJ-N1_dldy",
        lines: [199, 715, 381, 715, 475, 619],
        circles: [
          { x: 381, y: 715 },
          { x: 475, y: 619 },
        ],
        tipsPosition: {
          x: 204,
          y: 689,
        },
        ract: [{ x: 381, y: 715 }],
        text: [
          {
            x: 204,
            y: 689,
            text: "电流电压:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 276,
            y: 688,
            text: "27.00V",
            unit: "V",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "first_fdpl",
        key: "jrYYVrWZWVq_JX1-FDJ-N1_fdpl",
        lines: [287, 795, 489, 795, 605, 621],
        circles: [
          { x: 489, y: 795 },
          { x: 605, y: 621 },
        ],
        tipsPosition: {
          x: 296,
          y: 769,
        },
        ract: [{ x: 489, y: 795 }],
        text: [
          {
            x: 296,
            y: 769,
            text: "发电频率:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 369,
            y: 768,
            text: "18.88Hz",
            unit: "Hz",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "second_jyy",
        key: "jrYYVrWZWVq_JX1-FDJ-N1_jyy",
        lines: [383, 223, 568, 223, 611, 422],
        circles: [
          { x: 568, y: 223 },
          { x: 611, y: 422 },
        ],
        tipsPosition: {
          x: 419,
          y: 199,
        },
        ract: [{ x: 568, y: 223 }],
        text: [
          {
            x: 419,
            y: 199,
            text: "机油压:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 473,
            y: 198,
            text: "3.5Bar",
            unit: "Bar",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "second_ryw",
        key: "jrYYVrWZWVq_JX1-FDJ-N2_ryw",
        state: "",
        errorDatas: {
          // warnCount: "",
          // warnTime: 888,
        },
        tipsPosition: {
          x: 773,
          y: 160,
        },
        lines: [671, 486, 744, 181, 966, 181],
        circles: [
          { x: 744, y: 181 },
          { x: 671, y: 486 },
        ],
        ract: [{ x: 744, y: 181 }],
        text: [
          {
            x: 773,
            y: 160,
            text: "燃油位:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 825,
            y: 159,
            text: " 80.00%",
            unit: "%",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "second_sw",
        key: "jrYYVrWZWVq_JX1-FDJ-N2_sw",
        lines: [762, 454, 827, 285, 1009, 285],
        circles: [
          { x: 827, y: 285 },
          { x: 762, y: 454 },
        ],
        tipsPosition: {
          x: 855,
          y: 262,
        },
        ract: [{ x: 827, y: 285 }],
        text: [
          {
            x: 855,
            y: 262,
            text: "水温:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 893,
            y: 261,
            text: "27.00℃",
            unit: "℃",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "second_dldy",
        key: "jrYYVrWZWVq_JX1-FDJ-N2_dldy",
        state: "",
        errorDatas: {
          // warnCount: 1,
          // warnTime: 888,
        },
        tipsPosition: {
          x: 843,
          y: 377,
        },
        lines: [736, 587, 817, 399, 998, 399],
        circles: [
          { x: 817, y: 399 },
          { x: 736, y: 587 },
        ],
        ract: [{ x: 817, y: 399 }],
        text: [
          {
            x: 843,
            y: 377,
            text: "电流电压:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 910,
            y: 376,
            text: " 27.00V",
            unit: "V",
            fontSize: 19,
            textDecoration: "111",
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
      {
        name: "second_fdpl",
        key: "jrYYVrWZWVq_JX1-FDJ-N2_fdpl",
        lines: [869, 574, 821, 777, 1023, 777],
        circles: [
          { x: 821, y: 777 },
          { x: 869, y: 574 },
        ],
        tipsPosition: {
          x: 847,
          y: 755,
        },
        ract: [{ x: 821, y: 777 }],
        text: [
          {
            x: 847,
            y: 755,
            text: "发电频率:",
            fontSize: 16,
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
          {
            x: 920,
            y: 754,
            text: "18.88Hz",
            unit: "Hz",
            fontSize: 19,
            fontStyle: "bold",
            fontFamily: "Source Han Sans CN",
            fill: "#fff",
          },
        ],
      },
    ],
    monitorDatas: {
      activeTabs: "oneAlternator",
      activeMonitorState: "ONLINE",
      tabs: [{ label: "1#配电房", value: "oneAlternator" }],
      videoUrl: "https://uat.rlinkiot.com/live/live/34020000001320000024@34020000001320000024.flv",
      bannerList: [
        {
          pkdn: "jraXCrYXB5s:DH-20211013",
          label: "锦绣办公室监控",
          url: "https://uat.rlinkiot.com/live/live/34020000001320000024@34020000001320000024.flv",
          background: require("../assets/images/banner_background_temp.jpg"),
          monitorState: "ONLINE",
          active: true,
        },
        {
          label: "会议室监控视频",
          pkdn: "jraXCrYXB5s:DH-20211014",
          url: "https://uat.rlinkiot.com/live/live/34020000001320000025@34020000001310000001.flv",
          background: require("../assets/images/banner_background_temp2.jpg"),
          monitorState: "ONLINE",
          active: false,
        },
      ],
      defaultCard: "JF-WSD-0004",
      cardList: [
        {
          title: "发电机房-1#温湿度",
          productKey: "HrXb9rXZKwd",
          deviceName: "JF-WSD-0004",
          temperature: 0,
          humidity: 0,
        },
        {
          title: "发电机房-2#温湿度",
          productKey: "HrXb9rXZKwd",
          deviceName: "JF-WSD-0005",
          temperature: 0,
          humidity: 0,
        },
        {
          title: "发电机房-3#温湿度",
          productKey: "HrXb9rXZKwd",
          deviceName: "JF-WSD-0006",
          temperature: 0,
          humidity: 0,
        },
      ],
    },
  },
}
